name: Render and publish

on:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - name: Install required command line tools
        run: sudo apt-get install librsvg2-bin
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
